// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductModuleScssNamespace {
  export interface IProductModuleScss {
    actionButton: string;
    productAddToCartButton: string;
    productContainer: string;
    productDetailsContainer: string;
    productDetailsDescription: string;
    productDetailsDescriptionContainer: string;
    productDetailsDescriptionHeader: string;
    productDetailsId: string;
    productDetailsPrice: string;
    productDetailsStock: string;
    productDetailsTitle: string;
    productImageContainer: string;
    productScrollContainer: string;
  }
}

declare const ProductModuleScssModule: ProductModuleScssNamespace.IProductModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductModuleScssNamespace.IProductModuleScss;
};

export = ProductModuleScssModule;
