// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FilterBarModuleScssNamespace {
  export interface IFilterBarModuleScss {
    filterBarContainer: string;
    filterBarItemLeft: string;
    filterBarItemRight: string;
    filterBarOptionsRowContainer: string;
    filterBarOptionsRowItem: string;
    filterBarRowContainer: string;
    filterBarSearchItem: string;
    filterBarSectionContainer: string;
    filterBarSectionContainerRight: string;
    open: string;
  }
}

declare const FilterBarModuleScssModule: FilterBarModuleScssNamespace.IFilterBarModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FilterBarModuleScssNamespace.IFilterBarModuleScss;
};

export = FilterBarModuleScssModule;
