// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CartModuleScssNamespace {
  export interface ICartModuleScss {
    cartContainer: string;
    cartRow: string;
    cartScrollContainer: string;
  }
}

declare const CartModuleScssModule: CartModuleScssNamespace.ICartModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CartModuleScssNamespace.ICartModuleScss;
};

export = CartModuleScssModule;
