// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BrowseModuleScssNamespace {
  export interface IBrowseModuleScss {
    shopCardButton: string;
    shopCardContainer: string;
    shopCardId: string;
    shopCardImg: string;
    shopCardPrice: string;
    shopCardRowActions: string;
    shopCardRowId: string;
    shopCardStock: string;
    shopCardTitle: string;
    shopCardsContainer: string;
  }
}

declare const BrowseModuleScssModule: BrowseModuleScssNamespace.IBrowseModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: BrowseModuleScssNamespace.IBrowseModuleScss;
};

export = BrowseModuleScssModule;
