// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CommonComponentsModuleScssNamespace {
  export interface ICommonComponentsModuleScss {
    actionButton: string;
  }
}

declare const CommonComponentsModuleScssModule: CommonComponentsModuleScssNamespace.ICommonComponentsModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CommonComponentsModuleScssNamespace.ICommonComponentsModuleScss;
};

export = CommonComponentsModuleScssModule;
