// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContentRootModuleScssNamespace {
  export interface IContentRootModuleScss {
    contentRoot: string;
  }
}

declare const ContentRootModuleScssModule: ContentRootModuleScssNamespace.IContentRootModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContentRootModuleScssNamespace.IContentRootModuleScss;
};

export = ContentRootModuleScssModule;
