// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FilterbarModuleScssNamespace {
  export interface IFilterbarModuleScss {
    filterBarContainer: string;
    filterBarItemLeft: string;
    filterBarItemRight: string;
  }
}

declare const FilterbarModuleScssModule: FilterbarModuleScssNamespace.IFilterbarModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FilterbarModuleScssNamespace.IFilterbarModuleScss;
};

export = FilterbarModuleScssModule;
