// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NavbarModuleScssNamespace {
  export interface INavbarModuleScss {
    navMainElement: string;
    navSideElement: string;
  }
}

declare const NavbarModuleScssModule: NavbarModuleScssNamespace.INavbarModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NavbarModuleScssNamespace.INavbarModuleScss;
};

export = NavbarModuleScssModule;
