// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NotFoundModuleScssNamespace {
  export interface INotFoundModuleScss {
    errorContainer: string;
    textContainer: string;
  }
}

declare const NotFoundModuleScssModule: NotFoundModuleScssNamespace.INotFoundModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NotFoundModuleScssNamespace.INotFoundModuleScss;
};

export = NotFoundModuleScssModule;
