name: pnpm-setup
on:
  workflow_call:
    inputs:
      workingDir:
        required: true
        type: string
jobs:
  reusable-pnpm-setup:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ inputs.workingDir }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.0
          run_install: true
